### ISSUE TITLE
Zoom plugin is not working on the Moodle 4.0 

### ISSUE THREAD

**Issue by Megha271** [linkstreet/moodle-mod_zoom#41]
**Describe the bug**
After installing moodle version 4 on the demo site, I created the zoom meetings using the support id and I got an error.

**URL: demo.linkstreet.in
Username: support@linkstreet.in(assigned as a teacher)
Password: Welcome#123**

**To Reproduce**

1. Log in as a Support id 
2. Go to the assigned course and add an activity or resources
3. Click on the zoom meetings and see an error

![Screenshot from 2022-06-15 12-56-13](https://user-images.githubusercontent.com/81364875/173783117-b1ec49c7-e77b-4c5d-8d3a-5c55e390fdaf.png)

**Expected behavior**
The zoom event activity should be worked through the latest Moodle version.

**Comment by Ash-5** [comment]
@Megha271 Can you tell me a course where support@linkstreet.in in enrolled as a teacher because in **demo.linkstreet.in** I cannot see any user with **support@linkstreet.in**

**Comment by Megha271** [comment]
@Ash-5 please go through this course link
Course Name: Demo course
Course Link: https://demo.linkstreet.in/course/view.php?id=152

**Comment by Ash-5** [comment]
@Megha271 Fix for this issue is deployed into our demo site. Can you please validate that this issue happens no more.

**Comment by Megha271** [comment]
@Ash-5 There was an error message when downloading the records.
![Screenshot from 2022-07-08 09-33-02](https://user-images.githubusercontent.com/81364875/177915491-27f38e2a-21fc-4165-b39d-13d35db6794d.png)

**Comment by Megha271** [comment]
@Ash-5 Except for download, the rest of the things are working fine and closing this issue.

**Comment by Ash-5** [comment]
@meyyappanv requesting you to merge linkstreet/dev branch to linkstreet/stable branch and create a tag so that we can keep this plugin ready for the time of moodle 4 upgrade.

**Comment by meyyappanv** [comment]
@Ash-5 done, please validate. Sorry for the delay
