### ISSUE TITLE
Unable to download the zoom records on moodle

### ISSUE THREAD

**Issue by Megha271** [linkstreet/moodle-mod_zoom#43]
**Describe the bug**
After finishing the session, while clicking on the download, the records are not downloading. 

**To Reproduce**

1. Log in as a Support / Admin
2. Go to the assigned course and click on the finished zoom meeting
3. Click on the download button and see an error

![Screenshot from 2022-07-08 09-33-02](https://user-images.githubusercontent.com/81364875/177939753-cff3992b-c504-49c0-a71e-d100d7306884.png)

**Expected behavior**
If we click on the download button the records should be downloaded.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser Chrome,Firefox]

**Comment by nayanasQA** [comment]
@Ash-5 Could you please confirm, why this issue was closed? Could you please let us know about the challenges for this fix?

@Naveen1895 FYI
